"""
Regenerate `constraints.txt`: exact versions for everything `requirements.txt` pulls in.

    python scripts/freeze_constraints.py

`requirements.txt` pins the direct dependencies; this file pins the transitive ones
(numba, llvmlite, pandas, starlette, ...), so Render, Docker and CI install the same
set (`pip install -r requirements.txt -c constraints.txt`). Direct dependencies are
left out on purpose: a version bump to one of them then needs no second edit here,
and a bump whose new transitive requirements clash with these pins fails CI until
this script is re-run.

It installs into a fresh, throwaway virtual environment with this interpreter. Run it
with Python 3.11 (the version every host uses). Packages that only install on another
platform (uvloop, Linux only) are not pinned when it runs on Windows.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
import venv
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
REQUIREMENTS = BACKEND / "requirements.txt"
OUT = BACKEND / "constraints.txt"
TOOLING = {"pip", "setuptools", "wheel"}
# Pinned exactly by a direct dependency (pydantic pins its core), so a pin here adds
# nothing and can only clash: Dependabot bumped pydantic-core alone once, and the
# install failed (PR #12).
DETERMINED = {"pydantic-core"}


def _name(spec: str) -> str:
    return re.split(r"[=<>!~\[; ]", spec, maxsplit=1)[0].strip().lower().replace("_", "-")


def main() -> int:
    direct = {
        _name(line)
        for line in REQUIREMENTS.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    with tempfile.TemporaryDirectory(prefix="algoviz-freeze-") as tmp:
        venv.create(tmp, with_pip=True)
        py = Path(tmp) / ("Scripts/python.exe" if sys.platform == "win32" else "bin/python")
        subprocess.run([py, "-m", "pip", "install", "-q", "-r", REQUIREMENTS], check=True)
        frozen = subprocess.run(
            [py, "-m", "pip", "freeze", "--all"], check=True, capture_output=True, text=True
        ).stdout.splitlines()
    pins = sorted(
        (line for line in frozen if _name(line) not in direct | TOOLING | DETERMINED),
        key=_name,
    )
    header = (
        "# Transitive runtime dependencies, pinned: generated by scripts/freeze_constraints.py\n"
        f"# from requirements.txt with Python {sys.version_info.major}.{sys.version_info.minor}"
        f" on {sys.platform}. Do not edit by hand.\n"
    )
    OUT.write_text(header + "\n".join(pins) + "\n", encoding="utf-8", newline="\n")
    print(
        f"wrote {OUT.name}: {len(pins)} transitive pins ({len(direct)} direct in requirements.txt)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
